apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-group
  labels: 
    app: delivery-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-consumer
  template:
    metadata:
      labels:
        app: delivery-consumer
    spec:
      hostAliases: 
      - ip: "52.213.38.208"
        hostnames: 
        - "ip-172-31-7-133.eu-west-1.compute.internal"
      - ip: "18.202.250.11"
        hostnames: 
        - "ip-172-31-32-34.eu-west-1.compute.internal"
      - ip: "54.171.156.36"
        hostnames: 
        - "ip-172-31-8-59.eu-west-1.compute.internal"
      - ip: "54.76.46.203"
        hostnames: 
        - "ip-172-31-30-37.eu-west-1.compute.internal"
      imagePullSecrets:
      - name: landauhubkey
      containers:
      - name: generic-consumer
        image: thehuub/generic-consumer:v1.0.4
        imagePullPolicy: Always
        resources:
          requests: 
            memory: "1.5Gi"
            cpu: "500m"
          limits: 
            memory: "2Gi"
            cpu: "500m"
        env: 
        - name: BQ_TABLE
          value: "delivery_events_temp"
        - name: IMPORT_PATH
          value: "contracts.delivery.delivery_events_v10"
        - name: IMPORT_OBJECT
          value: "DeliveryEventsV10Topic"
        - name: IGNORE_EVENTS
          value: "[]"
        - name: CONSUME_ENV
          value: "prod"
        - name: WRITE_ENV
          value: "uat"
        - name: GROUP_ID
          value: "generic_delivery_DE4"
