apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: data-engineering-dev
  name: controller-role-binding
subjects:
- kind: ServiceAccount 
  name: controller-service-account
  apiGroup: ""
roleRef: 
  kind: Role
  name: controller-role
  apiGroup: ""

